### ISSUE TITLE
Копиране на резултата

### ISSUE THREAD

**Issue by NTsvetkov** [ggerganov/wordle-bg#11]
На десктоп на firefox и на телефон на brave крайният резултат се копира в клипборда. 
На десктоп на chrome излиза диалог за споделяне, но в клипборда няма нищо.

**Comment by provigz** [comment]
Промяната бе направена в #9, тъй като се очаква диалогът за споделяне да предлага опцията за копиране в клипборда.

Изглежда обаче, че диалогът за споделяне на Windows не предоставя такава опция... :\ [Изглежда и MacOS също](https://stackoverflow.com/questions/63466047/copy-option-missing-from-safari-desktop-web-share-api).

Потенциални решения:

* Слагане на филтри за забраняване на диалога за споделяне на операционните системи с този проблем.
* Добавяне на отделен бутон за директно копиране в клипборда, правейки бутона за споделяне единствено необходим при нуждата от директно споделяне чрез друго приложение.

Лично предпочитам второто решение.

**Comment by NTsvetkov** [comment]
За съжаление при мен показва скайп и windows mail. Опитах със скайп, но само го отвори и до там. Не им ползвам пощата, обаче подозирам, че резултатът ще е сходен.

Честно казано, за мен само копиране в клипборда ще е напълно достатъчно. Всеки може да пейстне където му е необходимо. Няколко човека цъкаме 6 разновидности на уърдъл. Същото споделяне като тук излиза само на още една. На останалите е само в клипборда.

Не знам, може да има хора, които да ползват нещо различно.

**Comment by provigz** [comment]
> Честно казано, за мен само копиране в клипборда ще е напълно достатъчно.

И за мен така, но вярвам, че диалоговия прозорец за споделяне би бил полезен за някои хора, особено на мобилни устройства. Иначе няма особено значение и за мен, лично. Не съм сигурен каква важност тя притежава в проекта.

**Comment by ggerganov** [comment]
Аз лично ползвам диалоговия прозорец на iOS понеже мога по-бързо да споделя резултата в чат групата, в която си споделяме - спестява ми "Home -> Chat App -> Chat group -> Paste"

Добавяне на нов бутон не е желателно. Ако можем да филтрираме платформите с този проблем, да пробваме това. Но ако се окаже трудно, може да се наложи да върнем копирането в клипборд безусловно

**Comment by NTsvetkov** [comment]
Сега копира. За съжаление в хром не излиза съобщение, че е копирано в клипборда, но ще го преживеем. Благодаря!

**Comment by provigz** [comment]
Тъкмо това и аз забелязах.

Трябва да се приложи този diff:

```
diff --git a/src/index-tmpl.html b/src/index-tmpl.html
index a3f9037..43c0331 100644
--- a/src/index-tmpl.html
+++ b/src/index-tmpl.html
@@ -168,7 +168,7 @@ <h2>Уърдъл</h2>
             function init() {
                 // If sharing is supported, hide the "Results copied to clipboard" text by default.
                 // The text will be shown only if sharing fails.
-                if (navigator.share) {
+                if (navigator.share && isMobile) {
                     Module.set_clipboard_text_visible(false);
                 }
 
```
