### ISSUE TITLE
Dictionary is Russian and not Bulgarian?

### ISSUE THREAD

**Issue by mfonville** [ggerganov/wordle-bg#5]
It seems the dictionary has many Russian words that are not Bulgarian. Are you sure about the dictionary that is used?

**Comment by ggerganov** [comment]
The dictionary is Bulgarian. The Bulgarian and Russian languages have many common words

**Comment by mfonville** [comment]
Yeah, I know some words are the same. But there are some words in the list that were not recognized by some native speakers, like "ТРЕФА". Could be of course that either they are just not acquainted with the word, but wondered if there are maybe not some loan or imported words from e.g. dialects or other languages in the list.

**Comment by ggerganov** [comment]
"ТРЕФА" means "clubs" in game of cards. I think it is a slang, so that is why most people don't know it.

**Comment by mfonville** [comment]
Ok thanks for your clarification!
