### ISSUE TITLE
Символът за „ер малък“ прави невалидни думи

### ISSUE THREAD

**Issue by zelenkroki** [ggerganov/wordle-bg#6]
Днешната дума (кьоше) прилича на нерешима.
Играя с виртуалната клавиатура, windows 7, браузър Version 109.0.5414.120 (Official Build) (64-bit).
https://zelenkroki.files.wordpress.com/2023/09/nrpoznata_duma.jpg

**Comment by triple-espress0** [comment]
Поведението е същото и на устройство с Android 13 и браузър Firefox 117.1.0. 
![Screenshot_20230919-080925](https://github.com/ggerganov/wordle-bg/assets/108225433/d5a996b1-7d89-4f7a-a404-abc2cdd7db9f)

**Comment by ggerganov** [comment]
Здравейте,

Съжалявам, имаше наистина проблем в играта.
Пробвайте да презаредите страницата (refresh) и би трябвало да се оправи.

Поздрави,
Георги

**Comment by triple-espress0** [comment]
Всичко е наред вече. Благодаря за адаптирането на увлекателната игра на български език и продължавайте в същия дух!

**Comment by iboB** [comment]
Fixed in #7

**Comment by zelenkroki** [comment]
Радвам се, че реагирахте толкова бързо. Благодаря и респект! :)
