### ISSUE TITLE
Бъг в днешната дума "пряка"

### ISSUE THREAD

**Issue by iboB** [ggerganov/wordle-bg#8]
Думата е пряка, както се вижда ако изиграеш случайни ходове до края, но играта решава че няма буквата "А".

Първо помислих че буква "А" от латиницата е попаднала в речника, но проверих и не е така. "ПРЯКА" в речника си е с букви от кирилицата и в него няма букви от латиницата.

За сега нямам идея

**Comment by ggerganov** [comment]
В тайния речник с отговорите е написана с латинско A 🤦 
Трябва да компилирам нова версия с коригирания речник - по-късно днес.

**Comment by iboB** [comment]
Можеш да спасиш частично положението с днешната игра ако смениш тук:

https://github.com/ggerganov/wordle-bg/blob/master/src/main.cpp#L996C34-L996C81

на `wordsDailyPool[(puzzleId + 1)%wordsDailyPool.size()];`

(Така от днес нататък ще е един ден напред завинаги)

**Comment by iboB** [comment]
Ама пък така тия които са играли някакви ходове ще се прецакат...

... но всъщност даже и да стане пряка `if (puzzleId == 643) g_state.answer = "ПРЯКА"` 

Пак ще се прецакат тези, които вече са играли 'а' някъде
